name: Deploy Lambda Function

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: MySimpleLambdaFunction
  AWS_ROLE_TO_ASSUME: arn:aws:iam::127489365181:role/lambda_dynamo_s3_role

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install AWS CLI
      run: pip install awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActionsLambdaDeployment

    - name: Zip the Lambda function
      run: zip function.zip lambda_function.py

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://function.zip \
          --publish

    - name: Clean up
      run: rm function.zip
